spring:
  application:
    name: study
  datasource:
    url: jdbc:h2:mem:study
    username: sa
    password: zmurilao
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-tarefas


